name: CI Nautobot Broker Nats

on:
  push:
    branches:
      - "main"
      - "dev"
      - "ltm-*"
    tags:
      - "v*"
  pull_request: ~

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "CI"
        uses: ./.github/actions/ci
