name: CI Nautobot Broker Nats

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
      - "dev"
      - "ltm-*"
  pull_request: ~

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "CI"
        uses: ./.github/actions/ci
