name: CI Nautobot Broker Nats

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
      - "dev"
      - "ltm-*"
  pull_request:
    types:
      - "labeled"

jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'Run CICD')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "CI"
        uses: ./.github/actions/ci
